[application]
nodeURL = "http://localhost:4545"
wsURL = "ws://localhost:4546"
contractAddress = "0xdD37c69fF29C4b93A346Ed6dF184f48A71800b7E"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"
port = 9001

[keystore]
agent = "/home/adrian/.ethereum/keystore/UTC--2020-06-26T19-00-23.241896464Z--bceda2ba9af65c18c7992849c312d1db77cf008e"

[passphrase]
agent = "Peru123."

[security]
permissionsEnabled = false
accountContractAddress = "0x4683519EF834572017Cb583246B717449A4B752c"
