[application]
nodeURL = "http://34.75.103.207:4545"
contractAddress = "0xE237a9bC6F8EF60Cd4cDc12d30C3d673b614d34C"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"

[keystore]
agent = "/home/adrian/.ethereum/keystore/UTC--2020-06-26T19-00-23.241896464Z--bceda2ba9af65c18c7992849c312d1db77cf008e"

[passphrase]
agent = "Peru123."