[application]
nodeURL = "http://34.75.159.76:4545"
contractAddress = "0xE2Aa96695EF268eCbf693d5ab276D5CBEA2A2251"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"
port = 9001

[keystore]
agent = "/home/adrian/.ethereum/keystore/UTC--2020-06-26T19-00-23.241896464Z--bceda2ba9af65c18c7992849c312d1db77cf008e"

[passphrase]
agent = "Peru123."

[security]
permissionsEnabled = true
accountContractAddress = "0x4683519EF834572017Cb583246B717449A4B752c"
