[application]
nodeURL = "http://34.75.103.207:4545"
contractAddress = "0x3F873228Ab0c9ab26f0b077e6374F8BabC5768D7"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"

[keystore]
agent = "/home/adrian/.ethereum/keystore/UTC--2020-06-26T19-00-23.241896464Z--bceda2ba9af65c18c7992849c312d1db77cf008e"

[passphrase]
agent = "Peru123."